name: 'Install Dependencies'
description: 'Install ASDF and required plugins'

runs:
  using: 'composite'
  steps:
    - name: Install ASDF and plugins
      shell: bash
      run: |
        git clone https://github.com/asdf-vm/asdf.git ${{ inputs.asdf_dir }} --branch ${{ inputs.asdf_version }} && . "${{ inputs.asdf_dir }}/asdf.sh"
        asdf plugin add caf-scripts "https://github.com/weareadaptive/asdf-caf-scripts"
        echo "" | tee -a .tool-versions > /dev/null
        echo "caf-scripts ref:${{ github.sha }}" >> .tool-versions
        cut -d' ' -f1 .tool-versions | xargs -I{} asdf plugin-add {} || true
        asdf install

    - name: Test caf_create_local_k8s
      shell: bash
      run: |
        . "${{ inputs.ASDF_DIR }}/asdf.sh"
        caf_create_local_k8s.sh

    - name: Test caf_route_to_local_k8s
      shell: bash
      run: |
        # Install ingress-nginx
        helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace nginx-ingress --create-namespace

        . "${{ inputs.ASDF_DIR }}/asdf.sh"
        caf_route_to_local_k8s.sh &
        curl -s --connect-timeout 5 --retry 5 --retry-delay 5 kube-dns.kube-system.svc.cluster.local:9153/metrics

inputs:
  asdf_version:
    description: 'ASDF version'
    required: true
  asdf_dir:
    description: 'ASDF directory'
    required: true