name: 'Test ASDF CAF Scripts'
description: 'Install ASDF and required plugins and test functionality of CAF scripts'

runs:
  using: 'composite'
  steps:
    - name: Test ASDF CAF Scripts
      shell: bash
      uses: asdf-vm/actions/plugin-test@v3
      with:
        command: caf_create_local_k8s.sh
        version: ref:${{ github.sha }}
        skip_install: ${{ inputs.skip_install }}

    - name: Install Ingress NGINX
      shell: bash
      run: |
        helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace nginx-ingress --create-namespace

    - name: Test ASDF CAF Scripts 2
      shell: bash
      uses: asdf-vm/actions/plugin-test@v3
      with:
        command: |
          caf_route_to_local_k8s.sh &
          echo "Attempting to curl kube-dns metrics endpoint..." && curl -s -o /dev/null --connect-timeout 5 --retry 5 --retry-delay 5 kube-dns.kube-system.svc.cluster.local:9153/metrics && echo "kube-dns metrics endpoint is reachable."
        version: ref:${{ github.sha }}
        skip_install: ${{ inputs.skip_install }}

inputs:
  skip_install:
    description: 'Skip installing ASDF'
    default: false